apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: code-server
  ports:
    - port: 443
      targetPort: {{ .Values.codeServer.containerPort }}
  type: {{ .Values.codeServer.serviceType }}

